name: thicktorrambles
favicon: null
layout_spectrum: 0.42606569989584386
typography_spectrum: 0.9690905530005693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7322586446534842
  lightness: 0.806741843232885
  saturation: 0.5826224389020354
  rhythmicContrast: 0.6997841824777424
purpose: []
